### ISSUE TITLE
The documentation should contain information on how to integrate the JS SDK with webpack (& possibly other bundlers) in a browser-only environment

### ISSUE THREAD

**Issue by simodrws** [nevermined-io/sdk-js#149]
## Is your feature request related to a problem? Please describe.
Integrating the JS SDK with create-react-app works flawlessly. The webpack configuration for CRA is "hidden" from the get-go and we need to "eject" the app to see the configuration. When ejecting, it is not visible which part of the config is responsible for the JS SDK working in a browser-only environment. 

When using a basic webpack configuration, shimming the modules in the "default webpack way"

```js
/* ... */
 resolve: {
    extensions: ['.js', '.jsx', '.ts', '.tsx'],
    fallback: {
      fs: false,
      tls: false,
      net: false,
      path: false,
      zlib: false,
      http: false,
      https: false,
      stream: false,
      crypto: false,
      os: false,
      assert: false
    }
```

fails. 

## Describe the solution you'd like
As a developer, I want to integrate the JS SDK in my browser-only project. There should be clear & concise steps on how to setup a custom webpack configuration for a BROWSER-ONLY project with using the NVM JS SDK. If a minimal working webpack browser-only configuration would be provided, that would be a good starting point.

**Comment by r-marques** [comment]
does this still make sense since now we have the catalog?

**Comment by aaitor** [comment]
probably don't, closing for now
