### ISSUE TITLE
Create an order method that supports the secondary market flow

### ISSUE THREAD

**Issue by r-marques** [nevermined-io/sdk-js#159]
### What

We want to extend the current `nevermined.nfts.order` method or create a new one that supports the secondary market flow.

### Why

We want to allow collectors to easily purchase nfts on the secondary market

### How

- The test case can be found here  https://github.com/nevermined-io/sdk-js/pull/157/files#diff-2acc1dda027dfa4182839f5bf68e3d75b1485ee2662ad8528ec1038a1b599768R405

**Comment by Elod23** [comment]
Closed in https://github.com/nevermined-io/sdk-js/pull/162/files. Was just a leftover, sorry @aaitor .
