### ISSUE TITLE
Minimize `sdk-js` library size

### ISSUE THREAD

**Issue by aaitor** [nevermined-io/sdk-js#226]
```
$ npx source-map-explorer dist/browser/sdk.cjs.min.js dist/browser/sdk.cjs.min.js.map
```
![source-map-explorer](https://user-images.githubusercontent.com/1793187/178235251-b5b529c7-71e3-452c-90b2-0c02c38a9269.png)

- [x] See if it's possible to replace circomlibjs
> _circomlibjs_ is responsible for a third of the sdk size

- [x] Consider replacing `bignumber.js` for `ethers.BigNumber`
> _ethers_ uses `BN.js` under the hood. If we use the same in the sdk we can remove the `bignumber.js` dependency but this is a breaking change for those integrating with the sdk

- [ ] make the rule `@typescript-eslint/no-unused-vars` an error by default https://typescript-eslint.io/rules/no-unused-vars/
- [x] remove the need for `@nevermined-io/contracts`

**Comment by r-marques** [comment]
update:
- replaced web3 with ethers.js
- removed data transfer proofs to own package

![Image](https://user-images.githubusercontent.com/1793187/180774092-d7ffab53-399d-48bc-90f4-8006ffa1a964.png)
