### ISSUE TITLE
Out of gas issue when sending back to back transactions

### ISSUE THREAD

**Issue by r-marques** [nevermined-io/sdk-js#32]
The test https://github.com/nevermined-io/sdk-js/blob/66cbea13f47df918805dfec27f7ef0031e9869cf/test/keeper/ContractEvent.test.ts#L60 fails randomly with `Out of gas` error.

This is probably because we are sending back to back transactions that are using the same nounce. This is an issue that happens also in the python sdk.

One of the solutions for this could be to manually increment the nounce and retry when we get this kind of error.

**Comment by eruizgar91** [comment]
I hope this get fixed with the change added in #51. We can check and if the error doesn't appear more, close this.
