### ISSUE TITLE
newGateway should be removed

### ISSUE THREAD

**Issue by dancespiele** [nevermined-io/sdk-js#395]
## Current Behavior

Currently we need to add in the `Config` to get the instance of the SDK the parameter `newGateway` otherwise we will get sometimes unauthorized when we try to download a NFT

## Expected Behavior

At least it shouldn't be necessary add that parameter to avoid unauthorized errors and if we won't maintain the SDK-py anymore it should be removed

**Comment by aaitor** [comment]
Merged into `develop` via: https://github.com/nevermined-io/sdk-js/pull/401/commits/4398b50d5bbf3cedec8d95741b31f6f2f06f40c0
