### ISSUE TITLE
Add support for 3rd party fee calculator

### ISSUE THREAD

**Issue by r-marques** [nevermined-io/sdk-js#404]
The sdk relies on on the web3 providers (infura, alchemy, ...) to get the gas price but this doesn't always work well specially when the network is congested.

Metamask on the other hand provides the option to get the gas price from some 3rd party service. The goal is to see if we can implement the same mechanism on the sdk.

Check https://docs.ethers.org/v6/api/providers/#FeeDataNetworkPlugin

from @ialberquilla 
```
not sure, but looks like the providers (infura and alchemy) are returning a low feeGasprice, the function used in the sdk to get the maxPriorityFeePerGas returns 1500000000 wei 15 GWEI and this is not getting mined, looking the price that is setting metamask is 120000000000 120 GWEI and gets mined in 20 seconds
chaning these values manually to 120000000000  works
```
```[tasklist]
### Tasks
- [x] Polygon fees calculation
- [x] Arbitrum fees calculation
```

**Comment by r-marques** [comment]
I will close this for now since we already added the ability to get the fees from a gas station for polygon networks

**Comment by aaitor** [comment]
We should consider Arbitrum too
