### ISSUE TITLE
Subscriptions.e2e.test not working

### ISSUE THREAD

**Issue by ialberquilla** [nevermined-io/sdk-js#424]
## Describe the bug

Executing the integration test Subscriptions.e2e.test poinint to Mumbai gets an error 'reason="execution reverted: Invalid marketplace fees'.

Looks like the test wasn't adapted after a change in the contracts to set up marketplaces fees. 

The error is thrown here https://github.com/nevermined-io/contracts/blob/de2aae22a7494e9debc840a7d64956b4c3870177/contracts/conditions/LockPaymentCondition.sol#L392

Looks like a fee should be added here https://github.com/nevermined-io/sdk-js/blob/4b146d1f2fc8c32b99159dfdf813329c41ff869d/integration/nevermined/Subscriptions.e2e.test.ts#L38

that matches with the fee in the contracts config, I tried setting 1000 that is what the keeper object has for getNetworkFee but does not work and with 1 considering decimals but is not working.

##  To Reproduce
1.
2.

**Comment by aaitor** [comment]
old issue already fixed
