### ISSUE TITLE
Assets and nfts improvements in sdk

### ISSUE THREAD

**Issue by dancespiele** [nevermined-io/sdk-js#552]
## Current behavior
The method `sdk.asset.download` require to DDO to have the service `access` to download the asset and the API of `sdk.nft721` require load a contract in order to use methods like `access` however such contract is not  used for theses methods

## Expected behavior
- [x] `sdk.asset.download` shouldn't require service `access` to DDO
- [ ] `sdk.nft721` should have available all the methods that doesn't require to load a contract for their logic

**Comment by aaitor** [comment]
NFT721Api require the loading of the contract because there is no a default contract deployed, the user needs to be specific about the nft-721 to use. 
This is better because avoid potential errors of the api
