### ISSUE TITLE
GenerateClientAssertion is giving an error

### ISSUE THREAD

**Issue by eruizgar91** [nevermined-io/sdk-js#606]
## Describe the bug

```Error: could not coalesce error (error={ "message": "ethereum.request is not a function" }, payload={ "id": 28, "jsonrpc": "2.0", "method": "eth_chainId", "params": [  ] }, code=UNKNOWN_ERROR, version=6.7.1)```

## To Reproduce

We are getting the following error when you call getNetworkId, in the generateClientAssertion. we need to check it because currently is causing an issue when you try to integrate the login in a frontend app.

## Screenshots

![image](https://github.com/nevermined-io/sdk-js/assets/3496824/ed223581-362f-4ba0-a2de-3fa3fd0a8734)

**Comment by aaitor** [comment]
Not a SDK problem. It was a problem with the integration.
