### ISSUE TITLE
Payment SDK Create Subscription and Create Webservice not working

### ISSUE THREAD

**Issue by Jovian-Dsouza** [nevermined-io/sdk-js#648]
## Describe the bug

Payment SDK Create Subscription and Create Webservice not working
```
async function createSubscription() {
    if (payments.isLoggedIn) {
      console.log('creating subscription')
      const params = {
        name: 'test subscription fdvd',
        description: 'test',
        price: 100000000n,
        tokenAddress: '0x75faf114eafb1BDbe2F0316DF893fd58CE46AA4d',
        amountOfCredits: 0,
        duration: 30,
        tags: ['test'],
      }
      console.log(params)
      const result = await payments.createSubscription(params)
      setSubscriptionDid(result.did)
      console.log(result)
    }
  }
```

## To Reproduce

1. build payments-nextjs-example
2. change enviroment to testing `environment: 'appTesting'`
3. Change Subscription Did for create web service
4. Call the function 

## Screenshots
![image](https://github.com/nevermined-io/sdk-js/assets/43859106/b7b5ab8f-9871-4218-a27a-d182d694f4ee)

![image](https://github.com/nevermined-io/sdk-js/assets/43859106/e41f5dc9-01d9-49ed-905a-be8c31167edc)

**Comment by aaitor** [comment]
Issue already resolved. Closing it
