### ISSUE TITLE
Flag --no-commons described in README for integration tests inexistent

### ISSUE THREAD

**Issue by Elod23** [nevermined-io/sdk-js#79]
## Describe the bug
While the README suggests to use the tools with the --no-commons flag, it is not available currently. 
README possibly outdated. 

## Expected behavior
Correct tools setup & starting flag is suggested in README.

**Comment by eruizgar91** [comment]
That's the old way that we were calling the marketplace, so I think we can get rid off this in the places that was not remove it.
